// This file is automatically generated. Do not edit it directly.
import { createClient } from '@supabase/supabase-js';
import type { Database } from './types';

const SUPABASE_URL = "https://azotmabbfcfyitzziimv.supabase.co";
const SUPABASE_PUBLISHABLE_KEY = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6ImF6b3RtYWJiZmNmeWl0enppaW12Iiwicm9sZSI6ImFub24iLCJpYXQiOjE3NDg2ODY1MzQsImV4cCI6MjA2NDI2MjUzNH0.qVQl9a9TjatSxWjL6EvdUInT_7X7zPve3rdJwataMDU";

// Import the supabase client like this:
// import { supabase } from "@/integrations/supabase/client";

export const supabase = createClient<Database>(SUPABASE_URL, SUPABASE_PUBLISHABLE_KEY);